apiVersion: v1
kind: Service
metadata:
  name: event-retriever
  labels:
    run: event-retriever
spec:
  ports:
  - port: 9001
    targetPort: 8001
    protocol: TCP
  # externalIPs: [""]

  selector:
    app: event-retriever
    #run: event-retriever
