apiVersion: apps/v1
kind: Deployment
metadata:
  name: back
spec:
  replicas: 3
  selector:
    matchLabels:
      component: back
  template:
    metadata:
      labels:
        component: back
    spec:
      containers:
        - name: back
          image: guoqiangqi/label-bot:0.55
          ports:
            - containerPort: 8008
