apiVersion: v1
kind: Service
metadata:
  name: data-cache
  labels:
    run: data-cache
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  # externalIPs: [""]

  selector:
    app: data-cache
