apiVersion: v1
kind: Service
metadata:
  name: rule-handler
  labels:
    run: rule-handler
spec:
  ports:
  - port: 9002
    targetPort: 5000
    protocol: TCP
#  externalIPs:
#    - 172.18.83.34
#    - 172.18.83.35
#    - 172.18.83.36

  selector:
    app: rule-handler
