apiVersion: v1
kind: Service
metadata:
  name: strategy-executor
  labels:
    run: strategy-executor
spec:
  ports:
  - port: 9003
    targetPort: 8002
    protocol: TCP
  # externalIPs: [""]

  selector:
    app: strategy-executor
